def appName = "springboot-sample-app"
def project = ""
def pom
node {
    stage("初始化环境") {
        project = env.PROJECT_NAME
    }
}
node("maven") {
    stage("下载代码") {
        git url: "https://github.com/xiaods/springboot-helloworld.git", branch: "master"
    }
    stage("配置依赖库") {
        pom = readMavenPom file: 'pom.xml'
    }
    stage("构建应用Jar包") {
        sh "mvn clean package -Popenshift"
        stash name: "jar", includes: "target/app.jar"
    }
}

node {
    stage("构建镜像") {
        unstash name: "jar"
        sh "oc start-build ${appName}-docker --from-file=target/app.jar --follow -n ${project}"
    }
    stage("部署应用") {
        openshiftDeploy deploymentConfig: appName, namespace: project
    }
    stage("标识应用版本") {
        openshiftTag srcStream: appName, srcTag: "latest", destStream: appName, destTag: pom.version, alias: "false"
    }
    stage("显示部署环境") {
        sh "printenv"
    }
}
